version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: react_docker_default
    command: >
      sh -c '
      if test -d node_modules;
      then
        echo node_modules_exists ;
      else
        cp -a /tmp/node_modules /usr/src/app/website;
      fi &&
      npm install && npm start
      '
    environment:
      COMPOSE_HTTP_TIMEOUT: 60000
      NODE_ENV: dev
    image: react_dev
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/src/app/:rw

